---
- name: "Ensure postgresql started/stopped"
  ansible.builtin.service:
    name: "{{ postgresql_service_name }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"
