---
- name: "Common | set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_os_family }}.yml"
    - "os-default.yml"
  tags:
    - always

- name: "Include repository tasks"
  ansible.builtin.include_tasks:
    file: repository-{{ ansible_os_family }}.yml
    apply:
      tags:
        - postgresql
        - postgresql:repository
  when: postgresql_supported and postgresql_repository
  tags:
    - always

- name: "Install packages"
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family }}.yml
    apply:
      tags:
        - postgresql
        - postgresql:packages
  when: postgresql_supported
  tags:
    - always

- name: "Initialize database"
  ansible.builtin.include_tasks:
    file: common-initialize.yml
    apply:
      tags:
        - postgresql
        - postgresql:setup
  when: postgresql_supported
  tags:
    - always

- name: "Configure postgresql"
  ansible.builtin.include_tasks:
    file: common-config.yml
    apply:
      tags:
        - postgresql
        - postgresql:config
  when: postgresql_supported
  tags:
    - always

- name: "Set systemd service"
  ansible.builtin.include_tasks:
    file: common-service.yml
    apply:
      tags:
        - postgresql
        - postgresql:setup
  when: postgresql_supported
  tags:
    - always

- name: "Set systemd service"
  ansible.builtin.include_tasks:
    file: common-service.yml
    apply:
      tags:
        - postgresql
        - postgresql:setup
  when: postgresql_supported
  tags:
    - always

- name: "Create database users"
  ansible.builtin.include_tasks:
    file: common-users.yml
    apply:
      tags:
        - postgresql
        - postgresql:users
  when: postgresql_supported and postgresql_service_state in ('started')
  tags:
    - always
