---

- name: "Install postgresql client"
  ansible.builtin.dnf:
    name: postgresql{{ postgresql_version }}
    state: present
  when: postgresql_install_client


- name: "Install postgresql server"
  ansible.builtin.dnf:
    name: postgresql{{ postgresql_version }}-server
    state: present
  when: postgresql_install_server


- name: "Install postgresql estra packages"
  ansible.builtin.dnf:
    name: postgresql{{ postgresql_version }}-{{ extra }}
    state: present
  loop: "{{ postgresql_packeges_extra }}"
  loop_control:
    loop_var: extra
